name: Update README

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: GitHub - Activity - Readme
      - uses: jamesgeorge007/github-activity-readme@v0.3.1

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
